apiVersion: v1
kind: Service
metadata:
  name: honey-backend
  namespace: honey-shop
spec:
  selector:
    app: honey-backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: LoadBalancer
